services:
  repro:
    build:
      context: .
      dockerfile: repro/Dockerfile
    image: einval-repro
    container_name: einval-repro
    # Required for tc/netem to work
    privileged: true
    environment:
      - REPRO_IGNORE_DUAL_STACK=false
      - MSW_USE_FIX
      - CONCURRENCY=300
      - REQUESTS=2000
    command: pnpm start
