services:
  repro:
    build:
      context: .
      dockerfile: repro/Dockerfile
    image: einval-repro
    container_name: einval-repro
    # Required for tc/netem to work
    privileged: true
    environment:
      - MSW_USE_FIX=${MSW_USE_FIX:-false}
      # If the tc/netem delay is in place, you don't really need this to be very high
      # Conversely, without delay, a sweet spot is about CONCURRENCY=300, REQUESTS=20000
      - CONCURRENCY=${CONCURRENCY:-20}
      - REQUESTS=${REQUESTS:-100}
    command: pnpm start
